MSProject/Controllers/ProjectResourcesController.cs
using Models.AppModel;
using MSProject.Models;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MSProject.Controllers
{
    public class ProjectResourcesController : Controller
    {
        private readonly ProjectContext db = new ProjectContext();

        // GET: ProjectResources
        public async Task<ActionResult> Index()
        {
            var projectResources = db.ProjectResources.Include(p => p.Resource).Include(p => p.Task);
            return View(await projectResources.ToListAsync());
        }

        // GET: ProjectResources/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var projectResources = await db.ProjectResources.FindAsync(id);
            if (projectResources == null)
            {
                return HttpNotFound();
            }
            return View(projectResources);
        }

        // GET: ProjectResources/Create
        public ActionResult Create()
        {
            ViewBag.ResourceId = new SelectList(db.Resources, "Id", "Name");
            ViewBag.ProjectTaskId = new SelectList(db.ProjectTasks, "Id", "Name");
            return View();
        }

        // POST: ProjectResources/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,ProjectTaskId,ResourceId")] ProjectResources projectResources)
        {
            if (ModelState.IsValid)
            {
                db.ProjectResources.Add(projectResources);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ResourceId = new SelectList(db.Resources, "Id", "Name", projectResources.ResourceId);
            ViewBag.ProjectTaskId = new SelectList(db.ProjectTasks, "Id", "Name", projectResources.ProjectTaskId);
            return View(projectResources);
        }

        // GET: ProjectResources/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var projectResources = await db.ProjectResources.FindAsync(id);
            if (projectResources == null)
            {
                return HttpNotFound();
            }
            ViewBag.ResourceId = new SelectList(db.Resources, "Id", "Name", projectResources.ResourceId);
            ViewBag.ProjectTaskId = new SelectList(db.ProjectTasks, "Id", "Name", projectResources.ProjectTaskId);
            return View(projectResources);
        }

        // POST: ProjectResources/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Id,ProjectTaskId,ResourceId")] ProjectResources projectResources)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectResources).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ResourceId = new SelectList(db.Resources, "Id", "Name", projectResources.ResourceId);
            ViewBag.ProjectTaskId = new SelectList(db.ProjectTasks, "Id", "Name", projectResources.ProjectTaskId);
            return View(projectResources);
        }

        // GET: ProjectResources/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var projectResources = await db.ProjectResources.FindAsync(id);
            if (projectResources == null)
            {
                return HttpNotFound();
            }
            return View(projectResources);
        }

        // POST: ProjectResources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var projectResources = await db.ProjectResources.FindAsync(id);
            db.ProjectResources.Remove(projectResources);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MSProject/Controllers/ProjectTasksController.cs
using Models.AppModel;
using MSProject.Models;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MSProject.Controllers
{
    public class ProjectTasksController : Controller
    {
        private readonly ProjectContext db = new ProjectContext();

        // GET: ProjectTasks
        public async Task<ActionResult> Index()
        {
            var projectTasks = db.ProjectTasks.Include(p => p.Project);
            return View(await projectTasks.ToListAsync());
        }

        // GET: ProjectTasks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var projectTask = await db.ProjectTasks.FindAsync(id);
            if (projectTask == null)
            {
                return HttpNotFound();
            }
            return View(projectTask);
        }

        // GET: ProjectTasks/Create
        public ActionResult Create()
        {
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name");
            return View();
        }

        // POST: ProjectTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,ProjectId,Name,OutlineNumber,OutlineLevel,Duration,ActualCost,Cost")] ProjectTask
                projectTask)
        {
            if (ModelState.IsValid)
            {
                db.ProjectTasks.Add(projectTask);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", projectTask.ProjectId);
            return View(projectTask);
        }

        // GET: ProjectTasks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var projectTask = await db.ProjectTasks.FindAsync(id);
            if (projectTask == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", projectTask.ProjectId);
            return View(projectTask);
        }

        // POST: ProjectTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Id,ProjectId,Name,OutlineNumber,OutlineLevel,Duration,ActualCost,Cost")] ProjectTask
                projectTask)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projectTask).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", projectTask.ProjectId);
            return View(projectTask);
        }

        // GET: ProjectTasks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var projectTask = await db.ProjectTasks.FindAsync(id);
            if (projectTask == null)
            {
                return HttpNotFound();
            }
            return View(projectTask);
        }

        // POST: ProjectTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var projectTask = await db.ProjectTasks.FindAsync(id);
            db.ProjectTasks.Remove(projectTask);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MSProject/Controllers/SelectProjectController.cs
using MSProject.Models;
using System.Linq;
using System.Web.Mvc;

namespace MSProject.Controllers
{
    public class SelectProjectController : Controller
    {
        private readonly IProjectContext _db;

        public SelectProjectController(IProjectContext projectContext)
        {
            _db = projectContext;
        }

        // GET: SelectProject
        public ActionResult Index()
        {
            return View(_db.Projects.ToList());
        }

        [HttpPost]
        public ActionResult Index(int projectId)
        {
            var pId = projectId;
            //int.TryParse(projectId, out pId);

            if (pId == 0) return View(_db.Projects.ToList());
            var project = _db.Projects.FirstOrDefault(p => p.Id == pId);
            if (project != null)
                ViewBag.SelectedProject = project.Name;
            return View(_db.Projects.ToList());
        }
    }
}

MSProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="description" content="The description of my page" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Data entry for Project", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li class="dropdown">
                        <!--
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">App <b class="create"></b></a>
                                                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown Example
                        <span class="caret"></span></button>
                                            -->
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Application
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Projects", "Index", "Projects")</li>
                            <li>@Html.ActionLink("Resources", "Index", "Resources")</li>
                            <li>@Html.ActionLink("Project Tasks", "Index", "ProjectTasks")</li>
                            <li>@Html.ActionLink("Task Resources", "Index", "ProjectResources")</li>
                            <li>@Html.ActionLink("Generate file", "Index", "SelectProject")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - @DateTime.Now.Year - Sridhar Sathya</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>